// Package text prints an msl.Module as .metal source. It is the only encoder:
// text is the wire format the metal frontend consumes, and output is
// byte-stable for a given IR.
package text

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/vertex-language/vvm/gpu/ir/msl"
)

// Print renders a module with the default options.
func Print(m *msl.Module) (string, error) { return NewPrinter(m).Print() }

// Printer renders a module to MSL source text. It does not validate: run
// msl.Verify separately so that work-in-progress modules stay printable.
type Printer struct {
	m        *msl.Module
	comments bool
	header   string
	indent   string
}

// NewPrinter creates a printer with the default header, four-space indent, and
// trailing comments enabled.
func NewPrinter(m *msl.Module) *Printer {
	return &Printer{m: m, comments: true, header: "Generated by vertex", indent: "    "}
}

// WithComments toggles trailing // comments.
func (p *Printer) WithComments(on bool) *Printer { p.comments = on; return p }

// WithHeader sets the header comment; "" disables the header block.
func (p *Printer) WithHeader(h string) *Printer { p.header = h; return p }

// WithIndent sets the indent unit.
func (p *Printer) WithIndent(s string) *Printer { p.indent = s; return p }

// Print renders the module.
func (p *Printer) Print() (string, error) {
	var b strings.Builder

	if p.header != "" {
		b.WriteString("//\n")
		for _, line := range strings.Split(p.header, "\n") {
			b.WriteString("// " + line + "\n")
		}
		b.WriteString("//\n\n")
	}
	if p.m.Version.Std() != "" {
		fmt.Fprintf(&b, "// -std=%s\n\n", p.m.Version.Std())
	}

	p.decls(&b, p.m.Decls)
	return b.String(), nil
}

// ----------------------------------------------------------- declarations

func (p *Printer) decls(b *strings.Builder, ds []msl.Decl) {
	prev := ""
	for i, d := range ds {
		kind := declKind(d)
		if i > 0 && (kind != prev || kind == "block") {
			b.WriteString("\n")
		}
		p.decl(b, d)
		prev = kind
	}
}

func declKind(d msl.Decl) string {
	switch d.(type) {
	case *msl.Include, *msl.Using:
		return "line"
	case *msl.VarDecl, *msl.Alias, *msl.CommentDecl:
		return "var"
	default:
		return "block"
	}
}

func (p *Printer) decl(b *strings.Builder, d msl.Decl) {
	switch v := d.(type) {
	case *msl.Include:
		if v.Local {
			fmt.Fprintf(b, "#include \"%s\"\n", v.Name)
		} else {
			fmt.Fprintf(b, "#include <%s>\n", v.Name)
		}
	case *msl.Using:
		fmt.Fprintf(b, "using namespace %s;\n", v.Namespace)
	case *msl.Alias:
		fmt.Fprintf(b, "using %s = %s;\n", v.Name, typeStr(v.Type))
	case *msl.CommentDecl:
		fmt.Fprintf(b, "// %s\n", v.Text)
	case *msl.RawDecl:
		b.WriteString(v.Text)
		if !strings.HasSuffix(v.Text, "\n") {
			b.WriteString("\n")
		}
	case *msl.VarDecl:
		b.WriteString(p.varLine(v) + ";" + p.trail(v.Comment) + "\n")
	case *msl.Struct:
		p.structDecl(b, v)
	case *msl.Function:
		p.function(b, v, "")
	case *msl.PPIfDecl:
		fmt.Fprintf(b, "#if %s\n", v.Cond)
		p.decls(b, v.Then)
		if v.Els != nil {
			b.WriteString("#else\n")
			p.decls(b, v.Els)
		}
		b.WriteString("#endif\n")
	}
}

func (p *Printer) structDecl(b *strings.Builder, s *msl.Struct) {
	fmt.Fprintf(b, "struct %s {\n", s.Name)
	for _, f := range s.Fields {
		b.WriteString(p.indent + declarator(f.Type, f.Name) + attrSuffix(f.Attrs) + ";\n")
	}
	for _, m := range s.Methods {
		b.WriteString("\n")
		p.function(b, m, p.indent)
	}
	b.WriteString("};\n")
}

// -------------------------------------------------------------- functions

func (p *Printer) function(b *strings.Builder, f *msl.Function, ind string) {
	for _, a := range f.Attrs {
		b.WriteString(ind + attrStr(a) + "\n")
	}

	ret := "void"
	if f.Ret != nil {
		ret = typeStr(f.Ret)
	}
	head := ret + " " + f.Name
	if f.Stage != msl.Plain {
		head = string(f.Stage) + " " + head
	}
	head = ind + head

	inline := head + "(" + paramsInline(f.Params) + ")" + attrSuffix(f.RetAttrs)

	entry := f.Stage == msl.KernelStage || f.Stage == msl.VertexStage ||
		f.Stage == msl.FragmentStage
	multi := (entry && len(f.Params) >= 2) || len(inline) > 100

	sig := inline
	if multi {
		sig = p.paramsAligned(head, f.Params) + attrSuffix(f.RetAttrs)
	}

	if f.Body == nil {
		b.WriteString(sig + ";\n")
		return
	}
	b.WriteString(sig + "\n" + ind + "{\n")
	p.block(b, f.Body, ind, 1)
	b.WriteString(ind + "}\n")
}

func paramsInline(ps []*msl.Param) string {
	parts := make([]string, len(ps))
	for i, pr := range ps {
		parts[i] = declarator(pr.Type, pr.Name) + attrSuffix(pr.Attrs)
	}
	return strings.Join(parts, ", ")
}

// paramsAligned prints one parameter per line with aligned type, name, and
// attribute columns. Alignment is deterministic so output stays byte-stable.
func (p *Printer) paramsAligned(head string, ps []*msl.Param) string {
	if len(ps) == 0 {
		return head + "()"
	}
	wType, wName := 0, 0
	for _, pr := range ps {
		if _, isArr := pr.Type.(msl.ArrayType); isArr {
			continue
		}
		if n := len(typeStr(pr.Type)); n > wType {
			wType = n
		}
		if n := len(pr.Name); n > wName {
			wName = n
		}
	}

	var b strings.Builder
	b.WriteString(head + "(\n")
	for i, pr := range ps {
		line := p.indent
		if arr, isArr := pr.Type.(msl.ArrayType); isArr {
			line += pad(typeStr(arr.Elem), wType+1) +
				pr.Name + "[" + strconv.Itoa(arr.Len) + "]"
		} else if len(pr.Attrs) == 0 {
			line += pad(typeStr(pr.Type), wType+1) + pr.Name
		} else {
			line += pad(typeStr(pr.Type), wType+1) +
				pad(pr.Name, wName+1) + attrList(pr.Attrs)
		}
		line = strings.TrimRight(line, " ")
		if i < len(ps)-1 {
			line += ",\n"
		} else {
			line += ")"
		}
		b.WriteString(line)
	}
	return b.String()
}

func pad(s string, w int) string {
	if len(s) >= w {
		return s + " "
	}
	return s + strings.Repeat(" ", w-len(s))
}

// ------------------------------------------------------------- statements

func (p *Printer) block(b *strings.Builder, blk *msl.Block, base string, depth int) {
	for _, s := range blk.Stmts() {
		p.stmt(b, s, base, depth)
	}
}

func (p *Printer) stmt(b *strings.Builder, s msl.Stmt, base string, depth int) {
	ind := base + strings.Repeat(p.indent, depth)
	switch v := s.(type) {
	case *msl.VarDecl:
		b.WriteString(ind + p.varLine(v) + ";" + p.trail(v.Comment) + "\n")
	case *msl.Assign:
		b.WriteString(ind + inlineStmt(v) + ";" + p.trail(v.Comment) + "\n")
	case *msl.ExprStmt:
		b.WriteString(ind + exprStr(v.X) + ";" + p.trail(v.Comment) + "\n")
	case *msl.Return:
		if v.X.IsZero() {
			b.WriteString(ind + "return;" + p.trail(v.Comment) + "\n")
		} else {
			b.WriteString(ind + "return " + exprStr(v.X) + ";" + p.trail(v.Comment) + "\n")
		}
	case *msl.IncDec:
		b.WriteString(ind + inlineStmt(v) + ";\n")
	case *msl.If:
		b.WriteString(ind + "if (" + exprStr(v.Cond) + ") {\n")
		p.block(b, v.Then, base, depth+1)
		p.elseChain(b, v.Els, base, depth, ind)
	case *msl.For:
		b.WriteString(ind + "for (" + inlineStmt(v.Init) + "; " +
			exprStr(v.Cond) + "; " + inlineStmt(v.Post) + ") {\n")
		p.block(b, v.Body, base, depth+1)
		b.WriteString(ind + "}\n")
	case *msl.While:
		b.WriteString(ind + "while (" + exprStr(v.Cond) + ") {\n")
		p.block(b, v.Body, base, depth+1)
		b.WriteString(ind + "}\n")
	case *msl.DoWhile:
		b.WriteString(ind + "do {\n")
		p.block(b, v.Body, base, depth+1)
		b.WriteString(ind + "} while (" + exprStr(v.Cond) + ");\n")
	case *msl.Switch:
		b.WriteString(ind + "switch (" + exprStr(v.Tag) + ") {\n")
		for _, c := range v.Cases {
			for _, val := range c.Vals {
				b.WriteString(ind + "case " + exprStr(val) + ":\n")
			}
			p.block(b, c.Body, base, depth+1)
			if !c.Fall {
				b.WriteString(ind + p.indent + "break;\n")
			}
		}
		if v.Def != nil {
			b.WriteString(ind + "default:\n")
			p.block(b, v.Def, base, depth+1)
			b.WriteString(ind + p.indent + "break;\n")
		}
		b.WriteString(ind + "}\n")
	case *msl.Scope:
		b.WriteString(ind + "{\n")
		p.block(b, v.Body, base, depth+1)
		b.WriteString(ind + "}\n")
	case *msl.PPIf:
		fmt.Fprintf(b, "#if %s\n", v.Cond)
		p.block(b, v.Then, base, depth)
		if v.Els != nil {
			b.WriteString("#else\n")
			p.block(b, v.Els, base, depth)
		}
		b.WriteString("#endif\n")
	case *msl.Break:
		b.WriteString(ind + "break;\n")
	case *msl.Continue:
		b.WriteString(ind + "continue;\n")
	case *msl.Comment:
		b.WriteString(ind + "// " + v.Text + "\n")
	case *msl.Blank:
		b.WriteString("\n")
	case *msl.RawStmt:
		for _, line := range strings.Split(v.Text, "\n") {
			if line == "" {
				b.WriteString("\n")
			} else {
				b.WriteString(ind + line + "\n")
			}
		}
	default:
		b.WriteString(ind + fmt.Sprintf("/* unknown stmt %T */\n", s))
	}
}

// elseChain collapses `else { if ... }` into `else if ...`.
func (p *Printer) elseChain(b *strings.Builder, els *msl.Block, base string, depth int, ind string) {
	if els == nil {
		b.WriteString(ind + "}\n")
		return
	}
	if els.Len() == 1 {
		if nested, ok := els.Stmts()[0].(*msl.If); ok {
			b.WriteString(ind + "} else if (" + exprStr(nested.Cond) + ") {\n")
			p.block(b, nested.Then, base, depth+1)
			p.elseChain(b, nested.Els, base, depth, ind)
			return
		}
	}
	b.WriteString(ind + "} else {\n")
	p.block(b, els, base, depth+1)
	b.WriteString(ind + "}\n")
}

func (p *Printer) varLine(v *msl.VarDecl) string {
	out := ""
	if v.Space != msl.NoSpace {
		out += string(v.Space) + " "
	}
	out += declarator(v.Type, v.Name) + attrSuffix(v.Attrs)
	if !v.Init.IsZero() {
		out += " = " + exprStr(v.Init)
	}
	return out
}

// inlineStmt renders a simple statement without semicolon, for for-clauses.
func inlineStmt(s msl.Stmt) string {
	switch v := s.(type) {
	case nil:
		return ""
	case *msl.VarDecl:
		out := declarator(v.Type, v.Name)
		if !v.Init.IsZero() {
			out += " = " + exprStr(v.Init)
		}
		return out
	case *msl.Assign:
		return exprStr(v.Dst) + " " + string(v.Op) + " " + exprStr(v.Src)
	case *msl.ExprStmt:
		return exprStr(v.X)
	case *msl.IncDec:
		return string(v.Op) + exprStr(v.X)
	default:
		return fmt.Sprintf("/* unsupported inline stmt %T */", s)
	}
}

func (p *Printer) trail(c string) string {
	if p.comments && c != "" {
		return "  // " + c
	}
	return ""
}

// ------------------------------------------------------------ expressions

func exprStr(e msl.Expr) string {
	if e.IsZero() {
		return ""
	}
	return nodeStr(e.Node)
}

// sub parenthesizes a child only when its precedence is looser than the
// context requires.
func sub(e msl.Expr, min int) string {
	if e.IsZero() {
		return ""
	}
	s := nodeStr(e.Node)
	if msl.Prec(e.Node) < min {
		return "(" + s + ")"
	}
	return s
}

func nodeStr(n msl.ExprNode) string {
	switch v := n.(type) {
	case msl.NameExpr:
		return string(v)
	case msl.RawExpr:
		return string(v)
	case msl.IntExpr:
		return strconv.FormatInt(int64(v), 10)
	case msl.UintExpr:
		return strconv.FormatUint(uint64(v), 10) + "u"
	case msl.FloatExpr:
		return floatStr(float64(v))
	case msl.BoolExpr:
		if v {
			return "true"
		}
		return "false"
	case *msl.BinaryExpr:
		p := msl.Prec(v)
		// Left-associative: the right operand needs one level tighter.
		return sub(v.L, p) + " " + string(v.Op) + " " + sub(v.R, p+1)
	case *msl.UnaryExpr:
		return string(v.Op) + sub(v.X, msl.PrecUnary)
	case *msl.IndexExpr:
		return sub(v.X, msl.PrecPostfix) + "[" + exprStr(v.Index) + "]"
	case *msl.MemberExpr:
		return sub(v.X, msl.PrecPostfix) + "." + v.Name
	case *msl.CallExpr:
		return v.Fn + targs(v.TArgs) + "(" + args(v.Args) + ")"
	case *msl.MethodExpr:
		return sub(v.X, msl.PrecPostfix) + "." + v.Name +
			targs(v.TArgs) + "(" + args(v.Args) + ")"
	case *msl.CtorExpr:
		return typeStr(v.Type) + "(" + args(v.Args) + ")"
	case *msl.CastExpr:
		return typeStr(v.Type) + "(" + exprStr(v.X) + ")"
	case *msl.CondExpr:
		return sub(v.Cond, msl.PrecTernary+1) + " ? " +
			exprStr(v.Then) + " : " + sub(v.Else, msl.PrecTernary)
	case *msl.ListExpr:
		return "{" + args(v.Elems) + "}"
	default:
		return fmt.Sprintf("/*unknown expr %T*/", n)
	}
}

func args(es []msl.Expr) string {
	parts := make([]string, len(es))
	for i, e := range es {
		parts[i] = exprStr(e)
	}
	return strings.Join(parts, ", ")
}

func targs(as []msl.TypeArg) string {
	if len(as) == 0 {
		return ""
	}
	parts := make([]string, len(as))
	for i, a := range as {
		if a.Type != nil {
			parts[i] = typeStr(a.Type)
		} else {
			parts[i] = exprStr(a.Val)
		}
	}
	return "<" + strings.Join(parts, ", ") + ">"
}

func floatStr(f float64) string {
	s := strconv.FormatFloat(f, 'g', -1, 64)
	if !strings.ContainsAny(s, ".eE") {
		s += ".0"
	}
	return s
}

// ------------------------------------------------------------------ types

// declarator renders "type name", placing array lengths at the declarator
// site: float tile[256].
func declarator(t msl.Type, name string) string {
	if arr, ok := t.(msl.ArrayType); ok {
		return typeStr(arr.Elem) + " " + name + "[" + strconv.Itoa(arr.Len) + "]"
	}
	return typeStr(t) + " " + name
}

func typeStr(t msl.Type) string {
	switch v := t.(type) {
	case nil:
		return "void"
	case msl.ScalarType:
		return string(v)
	case msl.NamedType:
		return string(v)
	case msl.ConstType:
		return "const " + typeStr(v.Elem)
	case msl.VecType:
		return fmt.Sprintf("%s%d", typeStr(v.Elem), v.N)
	case msl.MatType:
		return fmt.Sprintf("%s%dx%d", typeStr(v.Elem), v.Cols, v.Rows)
	case msl.PackedType:
		return fmt.Sprintf("packed_%s%d", typeStr(v.Elem), v.N)
	case msl.AtomicType:
		return "atomic_" + typeStr(v.Elem)
	case msl.ArrayType:
		return fmt.Sprintf("%s[%d]", typeStr(v.Elem), v.Len)
	case msl.PtrType:
		return fmt.Sprintf("%s %s*", v.Space, typeStr(v.Elem))
	case msl.RefType:
		return fmt.Sprintf("%s %s&", v.Space, typeStr(v.Elem))
	case msl.TextureType:
		return fmt.Sprintf("%s<%s, access::%s>", v.Kind, typeStr(v.Elem), v.Access)
	case msl.SamplerType:
		return "sampler"
	case msl.ImageBlockType:
		return fmt.Sprintf("imageblock<%s>", v.Layout)
	case msl.TemplateType:
		return v.Name + targs(v.Args)
	case msl.TensorType:
		tag := string(v.Kind)
		if v.Offset {
			tag += ", tensor_offset"
		}
		return fmt.Sprintf("tensor<%s %s, dextents<int, %d>, %s>",
			v.Space, typeStr(v.Elem), v.Rank, tag)
	case msl.CoopTensorType:
		return fmt.Sprintf("cooperative_tensor<%s, dextents<int, %d>>",
			typeStr(v.Elem), v.Rank)
	default:
		return fmt.Sprintf("/*unknown type %T*/", t)
	}
}

// ------------------------------------------------------------- attributes

func attrStr(a msl.Attr) string {
	if a.IsZero() {
		return ""
	}
	s := "[[" + string(a.Name)
	if len(a.Args) > 0 {
		s += "(" + strings.Join(a.Args, ", ") + ")"
	}
	return s + "]]"
}

func attrList(as []msl.Attr) string {
	parts := make([]string, 0, len(as))
	for _, a := range as {
		if !a.IsZero() {
			parts = append(parts, attrStr(a))
		}
	}
	return strings.Join(parts, " ")
}

func attrSuffix(as []msl.Attr) string {
	s := attrList(as)
	if s == "" {
		return ""
	}
	return " " + s
}