// Package text prints an msl.Module as .metal source. It is the only
// encoder: text is the wire format, and output is byte-stable for a
// given IR (deterministic temp naming, stable attribute ordering).
package text

import (
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/vertex-language/ir/msl"
)

// Printer renders a module to MSL source text.
type Printer struct {
	m        *msl.Module
	comments bool
	header   string
	lint     bool
	warnings []string
}

// NewPrinter creates a printer with the default header and trailing
// comments enabled.
func NewPrinter(m *msl.Module) *Printer {
	return &Printer{m: m, comments: true, header: "Generated by vertex"}
}

// WithComments toggles trailing // comments from statement Comment fields.
func (p *Printer) WithComments(on bool) *Printer { p.comments = on; return p }

// WithHeader sets the header comment text; "" disables the header block.
func (p *Printer) WithHeader(h string) *Printer { p.header = h; return p }

// WithLint toggles advisory version-gate warnings, retrievable from
// Warnings after Print. Lint findings are warnings, never errors.
func (p *Printer) WithLint(on bool) *Printer { p.lint = on; return p }

// Warnings returns lint findings from the most recent Print.
func (p *Printer) Warnings() []string { return p.warnings }

// Print renders the module. It returns an error only for structurally
// invalid modules (a Ptr/Ref with no address space, a kernel with a
// non-void return type, an unclosed block).
func (p *Printer) Print() (string, error) {
	p.warnings = nil
	if err := p.validate(); err != nil {
		return "", err
	}
	if p.lint {
		p.runLint()
	}

	var b strings.Builder

	if p.header != "" {
		b.WriteString("//\n")
		for _, line := range strings.Split(p.header, "\n") {
			b.WriteString("// " + line + "\n")
		}
		b.WriteString("//\n\n")
	}

	for _, inc := range p.m.Includes.Items() {
		fmt.Fprintf(&b, "#include <%s>\n", inc)
	}
	for _, ns := range p.m.UsingNamespaces {
		fmt.Fprintf(&b, "using namespace %s;\n", ns)
	}
	b.WriteString("\n")

	if fcs := p.m.FnConsts.Items(); len(fcs) > 0 {
		for _, fc := range fcs {
			fmt.Fprintf(&b, "constant %s %s [[function_constant(%d)]];\n",
				msl.TypeString(fc.Type), fc.Name, fc.Index)
		}
		b.WriteString("\n")
	}

	if cs := p.m.Consts.Items(); len(cs) > 0 {
		for _, c := range cs {
			fmt.Fprintf(&b, "constant %s %s = %s;\n",
				msl.TypeString(c.Type), c.Name, exprStr(c.Init))
		}
		b.WriteString("\n")
	}

	for _, s := range p.m.Structs.Items() {
		p.printStruct(&b, s)
		b.WriteString("\n")
	}

	funcs := p.m.Funcs.Items()
	for i, f := range funcs {
		p.printFunc(&b, f)
		if i < len(funcs)-1 {
			b.WriteString("\n")
		}
	}

	return b.String(), nil
}

// ---------------------------------------------------------------- structs

func (p *Printer) printStruct(b *strings.Builder, s *msl.Struct) {
	fmt.Fprintf(b, "struct %s {\n", s.Name)
	for _, f := range s.Fields.Items() {
		b.WriteString("    " + declarator(f.Type, f.Name))
		if !f.Attr.IsZero() {
			b.WriteString(" " + f.Attr.String())
		}
		b.WriteString(";\n")
	}
	b.WriteString("};\n")
}

// -------------------------------------------------------------- functions

func (p *Printer) printFunc(b *strings.Builder, f *msl.Function) {
	for _, a := range f.Attrs.Items() {
		b.WriteString(a.String() + "\n")
	}

	ret := "void"
	if f.Ret != nil {
		ret = msl.TypeString(f.Ret)
	}
	head := ret + " " + f.Name
	if f.Qualifier != "" {
		head = f.Qualifier + " " + head
	}

	params := f.Params.Items()

	// Inline form for short signatures.
	inline := head + "("
	for i, pr := range params {
		if i > 0 {
			inline += ", "
		}
		inline += paramStr(pr)
	}
	inline += ")"

	entry := f.Qualifier == "kernel" || f.Qualifier == "vertex" || f.Qualifier == "fragment"
	multiline := (entry && len(params) >= 2) || len(inline) > 100

	if f.Code == nil { // declaration only
		if multiline {
			p.writeMultilineSig(b, head, params)
			b.WriteString(";\n")
		} else {
			b.WriteString(inline + ";\n")
		}
		return
	}

	if multiline {
		p.writeMultilineSig(b, head, params)
		b.WriteString("\n{\n")
	} else {
		b.WriteString(inline + "\n{\n")
	}
	p.printStmts(b, f.Code.Body(), 1)
	b.WriteString("}\n")
}

func paramStr(pr msl.Param) string {
	s := declarator(pr.Type, pr.Name)
	if !pr.Attr.IsZero() {
		s += " " + pr.Attr.String()
	}
	return s
}

// writeMultilineSig prints one parameter per line with aligned type,
// name, and attribute columns.
func (p *Printer) writeMultilineSig(b *strings.Builder, head string, params []msl.Param) {
	b.WriteString(head + "(")
	if len(params) == 0 {
		b.WriteString(")")
		return
	}
	b.WriteString("\n")

	wType, wName := 0, 0
	for _, pr := range params {
		if _, isArr := pr.Type.(msl.ArrayType); isArr {
			continue // arrays fold the suffix into the name column; skip for widths
		}
		if n := len(msl.TypeString(pr.Type)); n > wType {
			wType = n
		}
		if n := len(pr.Name); n > wName {
			wName = n
		}
	}

	for i, pr := range params {
		line := "    "
		if arr, isArr := pr.Type.(msl.ArrayType); isArr {
			line += pad(msl.TypeString(arr.Elem), wType+1) +
				pr.Name + "[" + strconv.Itoa(arr.Len) + "]"
		} else {
			line += pad(msl.TypeString(pr.Type), wType+1)
			if pr.Attr.IsZero() {
				line += pr.Name
			} else {
				line += pad(pr.Name, wName+1) + pr.Attr.String()
			}
		}
		line = strings.TrimRight(line, " ")
		if i < len(params)-1 {
			line += ","
		} else {
			line += ")"
		}
		b.WriteString(line)
		if i < len(params)-1 {
			b.WriteString("\n")
		}
	}
}

func pad(s string, w int) string {
	if len(s) >= w {
		return s + " "
	}
	return s + strings.Repeat(" ", w-len(s))
}

// ------------------------------------------------------------- statements

func (p *Printer) printStmts(b *strings.Builder, stmts []msl.Stmt, depth int) {
	for _, s := range stmts {
		p.printStmt(b, s, depth)
	}
}

func (p *Printer) printStmt(b *strings.Builder, s msl.Stmt, depth int) {
	ind := strings.Repeat("    ", depth)
	switch v := s.(type) {
	case *msl.DeclStmt:
		b.WriteString(ind + stmtInline(v) + ";" + p.trail(v.Comment) + "\n")
	case *msl.AssignStmt:
		b.WriteString(ind + stmtInline(v) + ";" + p.trail(v.Comment) + "\n")
	case *msl.ExprStmt:
		b.WriteString(ind + exprStr(v.X) + ";" + p.trail(v.Comment) + "\n")
	case *msl.ReturnStmt:
		if v.X == nil {
			b.WriteString(ind + "return;" + p.trail(v.Comment) + "\n")
		} else {
			b.WriteString(ind + "return " + exprStr(v.X) + ";" + p.trail(v.Comment) + "\n")
		}
	case *msl.IfStmt:
		b.WriteString(ind + "if (" + exprStr(v.Cond) + ") {\n")
		p.printStmts(b, v.Then, depth+1)
		if v.Else != nil {
			b.WriteString(ind + "} else {\n")
			p.printStmts(b, v.Else, depth+1)
		}
		b.WriteString(ind + "}\n")
	case *msl.ForStmt:
		init, post := "", ""
		if v.Init != nil {
			init = stmtInline(v.Init)
		}
		if v.Post != nil {
			post = stmtInline(v.Post)
		}
		cond := ""
		if v.Cond != nil {
			cond = exprStr(v.Cond)
		}
		b.WriteString(ind + "for (" + init + "; " + cond + "; " + post + ") {\n")
		p.printStmts(b, v.Body, depth+1)
		b.WriteString(ind + "}\n")
	case *msl.WhileStmt:
		b.WriteString(ind + "while (" + exprStr(v.Cond) + ") {\n")
		p.printStmts(b, v.Body, depth+1)
		b.WriteString(ind + "}\n")
	case *msl.BreakStmt:
		b.WriteString(ind + "break;\n")
	case *msl.ContinueStmt:
		b.WriteString(ind + "continue;\n")
	case *msl.IncStmt:
		b.WriteString(ind + "++" + exprStr(v.X) + ";\n")
	case *msl.CommentStmt:
		b.WriteString(ind + "// " + v.Text + "\n")
	case *msl.BlankStmt:
		b.WriteString("\n")
	case *msl.RawStmt:
		for _, line := range strings.Split(v.Text, "\n") {
			if line == "" {
				b.WriteString("\n")
			} else {
				b.WriteString(ind + line + "\n")
			}
		}
	default:
		b.WriteString(ind + fmt.Sprintf("/* unknown stmt %T */\n", s))
	}
}

func (p *Printer) trail(c string) string {
	if p.comments && c != "" {
		return "  // " + c
	}
	return ""
}

// stmtInline renders a simple statement without semicolon or newline,
// for for-loop clauses and normal statement bodies.
func stmtInline(s msl.Stmt) string {
	switch v := s.(type) {
	case *msl.DeclStmt:
		out := ""
		if v.Space != "" {
			out += string(v.Space) + " "
		}
		out += declarator(v.Type, v.Name)
		if v.Init != nil {
			out += " = " + exprStr(v.Init)
		}
		return out
	case *msl.AssignStmt:
		return exprStr(v.Dst) + " " + v.Op + " " + exprStr(v.Src)
	case *msl.ExprStmt:
		return exprStr(v.X)
	case *msl.IncStmt:
		return "++" + exprStr(v.X)
	default:
		return fmt.Sprintf("/* unsupported inline stmt %T */", s)
	}
}

// declarator renders "type name", placing array lengths at the
// declarator site: float tile[256].
func declarator(t msl.Type, name string) string {
	if arr, ok := t.(msl.ArrayType); ok {
		return msl.TypeString(arr.Elem) + " " + name + "[" + strconv.Itoa(arr.Len) + "]"
	}
	return msl.TypeString(t) + " " + name
}

// ------------------------------------------------------------ expressions

func exprStr(e msl.Expr) string {
	switch v := e.(type) {
	case nil:
		return ""
	case msl.Ident:
		return string(v)
	case msl.IntLit:
		return strconv.FormatInt(int64(v), 10)
	case msl.UintLit:
		return strconv.FormatUint(uint64(v), 10) + "u"
	case msl.FloatLit:
		return floatStr(float64(v))
	case msl.BoolLit:
		if v {
			return "true"
		}
		return "false"
	case *msl.BinaryExpr:
		return operand(v.L) + " " + v.Op + " " + operand(v.R)
	case *msl.UnaryExpr:
		return v.Op + operand(v.X)
	case *msl.IndexExpr:
		return operand(v.Base) + "[" + exprStr(v.Index) + "]"
	case *msl.MemberExpr:
		return operand(v.Base) + "." + v.Name
	case *msl.Call:
		return v.Fn + "(" + argList(v.Args) + ")"
	case *msl.MethodCall:
		return operand(v.Base) + "." + v.Name + "(" + argList(v.Args) + ")"
	case *msl.CtorExpr:
		return msl.TypeString(v.Type) + "(" + argList(v.Args) + ")"
	case *msl.CastExpr:
		return msl.TypeString(v.Type) + "(" + exprStr(v.X) + ")"
	default:
		return fmt.Sprintf("/*unknown expr %T*/", e)
	}
}

// operand parenthesizes composite sub-expressions conservatively.
func operand(e msl.Expr) string {
	switch e.(type) {
	case *msl.BinaryExpr, *msl.UnaryExpr:
		return "(" + exprStr(e) + ")"
	default:
		return exprStr(e)
	}
}

func argList(args []msl.Expr) string {
	parts := make([]string, len(args))
	for i, a := range args {
		parts[i] = exprStr(a)
	}
	return strings.Join(parts, ", ")
}

func floatStr(f float64) string {
	s := strconv.FormatFloat(f, 'g', -1, 64)
	if !strings.ContainsAny(s, ".eE") {
		s += ".0"
	}
	return s
}

// -------------------------------------------------------------- validation

func (p *Printer) validate() error {
	var errs []string

	checkType := func(t msl.Type, where string) {
		walkType(t, func(tt msl.Type) {
			switch v := tt.(type) {
			case msl.PtrType:
				if v.Space == "" {
					errs = append(errs, where+": pointer type has no address space")
				}
			case msl.RefType:
				if v.Space == "" {
					errs = append(errs, where+": reference type has no address space")
				}
			}
		})
	}

	for _, c := range p.m.Consts.Items() {
		checkType(c.Type, "const "+c.Name)
	}
	for _, fc := range p.m.FnConsts.Items() {
		checkType(fc.Type, "function constant "+fc.Name)
	}
	for _, s := range p.m.Structs.Items() {
		for _, f := range s.Fields.Items() {
			checkType(f.Type, "struct "+s.Name+"."+f.Name)
		}
	}
	for _, f := range p.m.Funcs.Items() {
		where := "function " + f.Name
		if f.Qualifier == "kernel" && f.Ret != nil && f.Ret != msl.Void {
			errs = append(errs, where+": kernel functions must return void")
		}
		if f.Ret != nil {
			checkType(f.Ret, where+" return type")
		}
		for _, pr := range f.Params.Items() {
			checkType(pr.Type, where+" parameter "+pr.Name)
		}
		if f.Code != nil {
			if f.Code.Depth() != 0 {
				errs = append(errs, where+": body has unclosed block (missing End)")
			}
			walkStmts(f.Code.Body(), func(t msl.Type) { checkType(t, where+" body") })
		}
	}

	if len(errs) > 0 {
		return errors.New("msl/text: " + strings.Join(errs, "; "))
	}
	return nil
}

// ------------------------------------------------------------------ lint

func (p *Printer) runLint() {
	seen := map[string]bool{}
	warn := func(msg string) {
		if !seen[msg] {
			seen[msg] = true
			p.warnings = append(p.warnings, msg)
		}
	}
	check := func(t msl.Type) {
		walkType(t, func(tt msl.Type) {
			switch v := tt.(type) {
			case msl.ScalarType:
				if v == msl.BFloat && !p.m.Version.GTE(msl.Metal31) {
					warn("bfloat requires metal3.1 (module is " + p.m.Version.Std() + ")")
				}
			case msl.TensorType:
				if !p.m.Version.GTE(msl.Metal40) {
					warn("tensor types require metal4.0 (module is " + p.m.Version.Std() + ")")
				}
			}
		})
	}
	for _, c := range p.m.Consts.Items() {
		check(c.Type)
	}
	for _, fc := range p.m.FnConsts.Items() {
		check(fc.Type)
	}
	for _, s := range p.m.Structs.Items() {
		for _, f := range s.Fields.Items() {
			check(f.Type)
		}
	}
	for _, f := range p.m.Funcs.Items() {
		if f.Ret != nil {
			check(f.Ret)
		}
		for _, pr := range f.Params.Items() {
			check(pr.Type)
		}
		if f.Code != nil {
			walkStmts(f.Code.Body(), check)
		}
	}
}

// ------------------------------------------------------------------ walks

func walkType(t msl.Type, fn func(msl.Type)) {
	if t == nil {
		return
	}
	fn(t)
	switch v := t.(type) {
	case msl.VecType:
		walkType(v.Elem, fn)
	case msl.MatType:
		walkType(v.Elem, fn)
	case msl.PackedType:
		walkType(v.Elem, fn)
	case msl.AtomicType:
		walkType(v.Elem, fn)
	case msl.ArrayType:
		walkType(v.Elem, fn)
	case msl.PtrType:
		walkType(v.Elem, fn)
	case msl.RefType:
		walkType(v.Elem, fn)
	case msl.TextureType:
		walkType(v.Elem, fn)
	case msl.TensorType:
		walkType(v.Elem, fn)
	}
}

func walkExpr(e msl.Expr, fn func(msl.Type)) {
	switch v := e.(type) {
	case *msl.BinaryExpr:
		walkExpr(v.L, fn)
		walkExpr(v.R, fn)
	case *msl.UnaryExpr:
		walkExpr(v.X, fn)
	case *msl.IndexExpr:
		walkExpr(v.Base, fn)
		walkExpr(v.Index, fn)
	case *msl.MemberExpr:
		walkExpr(v.Base, fn)
	case *msl.Call:
		for _, a := range v.Args {
			walkExpr(a, fn)
		}
	case *msl.MethodCall:
		walkExpr(v.Base, fn)
		for _, a := range v.Args {
			walkExpr(a, fn)
		}
	case *msl.CtorExpr:
		walkType(v.Type, fn)
		for _, a := range v.Args {
			walkExpr(a, fn)
		}
	case *msl.CastExpr:
		walkType(v.Type, fn)
		walkExpr(v.X, fn)
	}
}

func walkStmts(stmts []msl.Stmt, fn func(msl.Type)) {
	for _, s := range stmts {
		switch v := s.(type) {
		case *msl.DeclStmt:
			walkType(v.Type, fn)
			walkExpr(v.Init, fn)
		case *msl.AssignStmt:
			walkExpr(v.Dst, fn)
			walkExpr(v.Src, fn)
		case *msl.ExprStmt:
			walkExpr(v.X, fn)
		case *msl.ReturnStmt:
			walkExpr(v.X, fn)
		case *msl.IfStmt:
			walkExpr(v.Cond, fn)
			walkStmts(v.Then, fn)
			walkStmts(v.Else, fn)
		case *msl.ForStmt:
			if v.Init != nil {
				walkStmts([]msl.Stmt{v.Init}, fn)
			}
			walkExpr(v.Cond, fn)
			if v.Post != nil {
				walkStmts([]msl.Stmt{v.Post}, fn)
			}
			walkStmts(v.Body, fn)
		case *msl.WhileStmt:
			walkExpr(v.Cond, fn)
			walkStmts(v.Body, fn)
		case *msl.IncStmt:
			walkExpr(v.X, fn)
		}
	}
}