// Package text prints stablehlo IR modules as MLIR textual assembly.
//
// The printer emits generic MLIR syntax by default — the spec itself
// sticks to generic syntax because prettyprinter output can change across
// releases, and byte-stability is a design requirement here.
// WithPrettyFuncs(true) opts in to the compact func.func header form while
// keeping op bodies generic.
//
// Text carries no compatibility guarantees; pipe the output through
// `stablehlo-translate --serialize --target=<version>` to produce a
// portable artifact.
package text

import (
	"fmt"
	"strings"

	"github.com/vertex-language/ir/stablehlo"
)

// Printer renders a Module to MLIR assembly.
type Printer struct {
	m           *stablehlo.Module
	comments    bool
	header      string
	lint        bool
	prettyFuncs bool
	warnings    []string
	warned      map[string]bool
}

// NewPrinter creates a printer with the default header and options.
func NewPrinter(m *stablehlo.Module) *Printer {
	return &Printer{m: m, header: "Generated by vertex", warned: map[string]bool{}}
}

// WithComments enables trailing // comments from Op.Comment.
func (p *Printer) WithComments(on bool) *Printer { p.comments = on; return p }

// WithHeader sets the header comment; "" disables it.
func (p *Printer) WithHeader(h string) *Printer { p.header = h; return p }

// WithLint enables advisory version-gate warnings, retrievable from
// Warnings after Print. Lint findings are warnings, never errors.
func (p *Printer) WithLint(on bool) *Printer { p.lint = on; return p }

// WithPrettyFuncs opts in to the compact func.func header form (arguments
// inline). Op bodies remain generic either way.
func (p *Printer) WithPrettyFuncs(on bool) *Printer { p.prettyFuncs = on; return p }

// Warnings returns lint findings collected during the last Print.
func (p *Printer) Warnings() []string { return p.warnings }

// Print renders the module. It returns an error only for structurally
// invalid modules (a Value used across function boundaries, a region
// closure that never called Return, a Func with results but no
// terminator).
func (p *Printer) Print() (string, error) {
	p.warnings = nil
	p.warned = map[string]bool{}

	var b strings.Builder
	if p.header != "" {
		fmt.Fprintf(&b, "// %s\n", p.header)
	}
	b.WriteString("module")
	if p.m.Name != "" {
		b.WriteString(" @" + p.m.Name)
	}
	if attrs := p.m.Attrs.All(); len(attrs) > 0 {
		b.WriteString(" attributes " + renderAttrDict(attrs))
	}
	b.WriteString(" {\n")
	for _, f := range p.m.Funcs.All() {
		if err := p.printFunc(&b, f); err != nil {
			return "", err
		}
	}
	b.WriteString("}\n")
	return b.String(), nil
}

// --- function printing ---

type fnState struct {
	names      map[stablehlo.Value]string
	valCounter int
	argCounter int
}

func (p *Printer) printFunc(b *strings.Builder, f *stablehlo.Func) error {
	st := &fnState{names: map[stablehlo.Value]string{}}

	params := f.Params.All()
	values := f.Params.Values()
	argNames := make([]string, len(params))
	for i, prm := range params {
		name := prm.Name
		if name == "" {
			name = fmt.Sprintf("arg%d", st.argCounter)
		}
		st.argCounter++
		argNames[i] = "%" + name
		st.names[values[i]] = "%" + name
	}

	// Declaration only.
	if f.Code == nil {
		b.WriteString("  func.func private @" + f.Name + "(")
		for i, prm := range params {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(prm.Type.String())
		}
		b.WriteString(")")
		b.WriteString(renderResults(f.Results))
		b.WriteString("\n")
		return nil
	}

	if len(f.Results) > 0 && !f.Code.Returned() {
		return fmt.Errorf("text: func @%s has results but no terminator", f.Name)
	}

	if p.prettyFuncs {
		b.WriteString("  func.func ")
		if f.Private {
			b.WriteString("private ")
		}
		b.WriteString("@" + f.Name + "(")
		for i, prm := range params {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(argNames[i] + ": " + prm.Type.String())
			if aa, ok := f.ArgAttrs[i]; ok {
				b.WriteString(" " + renderAttrDict([]stablehlo.NamedAttr{aa}))
			}
		}
		b.WriteString(")" + renderResults(f.Results) + " {\n")
		if err := p.printBody(b, f, st, f.Code.Ops(), "    "); err != nil {
			return err
		}
		b.WriteString("  }\n")
		return nil
	}

	// Generic form.
	b.WriteString(`  "func.func"() <{function_type = ` + functionType(params, f.Results) +
		`, sym_name = "` + f.Name + `"`)
	if f.Private {
		b.WriteString(`, sym_visibility = "private"`)
	}
	b.WriteString("}> ({\n  ^bb0(")
	for i, prm := range params {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(argNames[i] + ": " + prm.Type.String())
	}
	b.WriteString("):\n")
	if err := p.printBody(b, f, st, f.Code.Ops(), "    "); err != nil {
		return err
	}
	b.WriteString("  }) : () -> ()\n")
	return nil
}

// --- op printing ---

func (p *Printer) printBody(b *strings.Builder, f *stablehlo.Func, st *fnState,
	ops []*stablehlo.Op, indent string) error {
	for _, op := range ops {
		if err := p.printOp(b, f, st, op, indent); err != nil {
			return err
		}
	}
	return nil
}

func (p *Printer) printOp(b *strings.Builder, f *stablehlo.Func, st *fnState,
	op *stablehlo.Op, indent string) error {
	if p.lint {
		p.lintOp(f, op)
	}

	def := p.assignResults(st, op)

	// Raw escape hatch.
	if op.RawFormat != "" {
		args := make([]any, len(op.RawOperands))
		for i, v := range op.RawOperands {
			name, ok := st.names[v]
			if !ok {
				return fmt.Errorf("text: raw op in @%s uses a value defined in another function (or not at all)", f.Name)
			}
			args[i] = name
		}
		b.WriteString(indent + def + fmt.Sprintf(op.RawFormat, args...))
		p.writeComment(b, op)
		b.WriteString("\n")
		return nil
	}

	operandNames := make([]string, len(op.Operands))
	operandTypes := make([]string, len(op.Operands))
	for i, v := range op.Operands {
		name, ok := st.names[v]
		if !ok {
			return fmt.Errorf("text: op %q in @%s uses a value defined in another function (or not at all)", op.Name, f.Name)
		}
		operandNames[i] = name
		operandTypes[i] = v.Type().String()
	}

	b.WriteString(indent + def + `"` + op.Name + `"(` + strings.Join(operandNames, ", ") + ")")

	// Regions.
	if len(op.Regions) > 0 {
		b.WriteString(" (")
		for ri, r := range op.Regions {
			if ri > 0 {
				b.WriteString(", ")
			}
			b.WriteString("{\n")
			if len(r.Args()) > 0 {
				b.WriteString(indent + "^bb0(")
				for ai, av := range r.Args() {
					if ai > 0 {
						b.WriteString(", ")
					}
					name := fmt.Sprintf("%%arg%d", st.argCounter)
					st.argCounter++
					st.names[av] = name
					b.WriteString(name + ": " + av.Type().String())
				}
				b.WriteString("):\n")
			}
			if r.Body == nil || !r.Body.Returned() {
				return fmt.Errorf("text: a region of %q in @%s never called Return", op.Name, f.Name)
			}
			if err := p.printBody(b, f, st, r.Body.Ops(), indent+"  "); err != nil {
				return err
			}
			b.WriteString(indent + "}")
		}
		b.WriteString(")")
	}

	// Attributes.
	if len(op.Attrs) > 0 {
		b.WriteString(" " + renderAttrDict(op.Attrs))
	}

	// Signature.
	b.WriteString(" : (" + strings.Join(operandTypes, ", ") + ")")
	switch len(op.ResultTypes) {
	case 0:
		b.WriteString(" -> ()")
	case 1:
		b.WriteString(" -> " + op.ResultTypes[0].String())
	default:
		parts := make([]string, len(op.ResultTypes))
		for i, t := range op.ResultTypes {
			parts[i] = t.String()
		}
		b.WriteString(" -> (" + strings.Join(parts, ", ") + ")")
	}

	p.writeComment(b, op)
	b.WriteString("\n")
	return nil
}

// assignResults names the op's results and returns the "%N = " prefix.
func (p *Printer) assignResults(st *fnState, op *stablehlo.Op) string {
	results := op.Results()
	if len(results) == 0 {
		return ""
	}
	base := fmt.Sprintf("%%%d", st.valCounter)
	st.valCounter++
	if len(results) == 1 {
		st.names[results[0]] = base
		return base + " = "
	}
	for i, r := range results {
		st.names[r] = fmt.Sprintf("%s#%d", base, i)
	}
	return fmt.Sprintf("%s:%d = ", base, len(results))
}

func (p *Printer) writeComment(b *strings.Builder, op *stablehlo.Op) {
	if p.comments && op.Comment != "" {
		b.WriteString(" // " + op.Comment)
	}
}

// --- lint ---

func (p *Printer) lintOp(f *stablehlo.Func, op *stablehlo.Op) {
	target := p.m.TargetVersion()
	if !op.MinVersion.IsZero() && !target.GTE(op.MinVersion) {
		p.warn(fmt.Sprintf("%s requires StableHLO >= %s (target is %s)",
			shortName(op.Name), op.MinVersion, target))
	}
	check := func(t stablehlo.Type) {
		if feat, min, ok := stablehlo.TypeFeatureVersion(t); ok && !target.GTE(min) {
			p.warn(fmt.Sprintf("%s requires StableHLO >= %s (target is %s)", feat, min, target))
		}
	}
	for _, v := range op.Operands {
		check(v.Type())
	}
	for _, t := range op.ResultTypes {
		check(t)
	}
}

func (p *Printer) warn(msg string) {
	if !p.warned[msg] {
		p.warned[msg] = true
		p.warnings = append(p.warnings, msg)
	}
}

// --- rendering helpers ---

func renderAttrDict(attrs []stablehlo.NamedAttr) string {
	parts := make([]string, len(attrs))
	for i, a := range attrs {
		if a.Value == nil {
			parts[i] = a.Name
		} else {
			parts[i] = a.Name + " = " + a.Value.String()
		}
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func renderResults(results []stablehlo.Type) string {
	switch len(results) {
	case 0:
		return ""
	case 1:
		return " -> " + results[0].String()
	default:
		parts := make([]string, len(results))
		for i, t := range results {
			parts[i] = t.String()
		}
		return " -> (" + strings.Join(parts, ", ") + ")"
	}
}

func functionType(params []stablehlo.Param, results []stablehlo.Type) string {
	in := make([]string, len(params))
	for i, prm := range params {
		in[i] = prm.Type.String()
	}
	out := "()"
	switch len(results) {
	case 0:
	case 1:
		out = results[0].String()
	default:
		parts := make([]string, len(results))
		for i, t := range results {
			parts[i] = t.String()
		}
		out = "(" + strings.Join(parts, ", ") + ")"
	}
	return "(" + strings.Join(in, ", ") + ") -> " + out
}

func shortName(opName string) string {
	if i := strings.LastIndexByte(opName, '.'); i >= 0 {
		return opName[i+1:]
	}
	return opName
}