// Package text prints a ptx.Module as PTX assembly.
//
// The printer makes no decisions about mnemonics or qualifier ordering:
// those are derived from the IR by (*ptx.Instr).Mnemonic. This package
// controls layout only, so output is byte-stable for a given module.
package text

import (
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/vertex-language/vvm/gpu/ir/ptx"
)

const (
	indent     = "\t"
	opColumn   = 24 // operands start here, in the conventional ptxas style
	bytesPerLn = 16 // .section byte payload wrapping
)

// Printer renders a module.
type Printer struct {
	m        *ptx.Module
	header   string
	comments bool
}

// New returns a printer for m.
func New(m *ptx.Module) *Printer {
	return &Printer{m: m, header: "Generated by vertex"}
}

// WithHeader sets the leading comment block. An empty string disables it.
func (p *Printer) WithHeader(s string) *Printer { p.header = s; return p }

// WithComments enables trailing // comments from Instr.Comment.
func (p *Printer) WithComments(on bool) *Printer { p.comments = on; return p }

// Print renders the module. It returns an error only for modules that cannot
// produce valid text at all; use ptx.Verify for everything else.
func Print(m *ptx.Module) (string, error) { return New(m).Print() }

func (p *Printer) Print() (string, error) {
	m := p.m
	if m.AddressSize != ptx.Addr32 && m.AddressSize != ptx.Addr64 {
		return "", errors.New("ptx: .address_size must be 32 or 64")
	}
	if m.Version.IsZero() {
		return "", errors.New("ptx: .version is required")
	}

	var b strings.Builder

	if p.header != "" {
		b.WriteString("//\n// " + p.header + "\n//\n")
	}
	b.WriteString(".version " + m.Version.String() + "\n")
	b.WriteString(".target " + m.Target.String())
	for _, o := range m.TargetOpts {
		b.WriteString(", " + o.String())
	}
	b.WriteString("\n")
	b.WriteString(".address_size " + strconv.Itoa(int(m.AddressSize)) + "\n")

	if m.BlocksAreClusters {
		b.WriteString(".blocksareclusters\n")
	}
	for _, pr := range m.Pragmas {
		b.WriteString(".pragma " + strconv.Quote(pr) + ";\n")
	}

	if files := m.Files(); len(files) > 0 {
		b.WriteString("\n")
		for _, f := range files {
			b.WriteString(".file " + strconv.Itoa(f.Index) + " " + strconv.Quote(f.Name))
			if f.Timestamp != 0 || f.Size != 0 {
				b.WriteString(", " + strconv.FormatUint(f.Timestamp, 10))
				b.WriteString(", " + strconv.FormatUint(f.Size, 10))
			}
			b.WriteString("\n")
		}
	}

	for _, d := range m.Decls() {
		b.WriteString("\n")
		switch x := d.(type) {
		case *ptx.Var:
			b.WriteString(varDecl(x) + "\n")
		case *ptx.Proto:
			b.WriteString(protoDecl(x) + "\n")
		case *ptx.Alias:
			b.WriteString(".alias " + x.Name + ", " + x.Target.Name + ";\n")
		case *ptx.Section:
			b.WriteString(sectionDecl(x))
		case *ptx.Kernel:
			p.kernel(&b, x)
		case *ptx.Func:
			p.function(&b, x)
		}
	}
	return b.String(), nil
}

// ---- Declarations ---------------------------------------------------------

func varDecl(v *ptx.Var) string {
	var parts []string
	if s := v.Linkage.String(); s != "" {
		parts = append(parts, s)
	}
	parts = append(parts, v.Space.String())
	if v.Align != 0 {
		parts = append(parts, ".align "+strconv.Itoa(v.Align))
	}
	if v.Vec != 0 {
		parts = append(parts, ".v"+strconv.Itoa(v.Vec))
	}
	parts = append(parts, v.Type.String())

	name := v.Name
	switch {
	case v.Len < 0:
		name += "[]"
	case v.Len > 0:
		name += "[" + strconv.Itoa(v.Len) + "]"
	}
	parts = append(parts, name)

	s := strings.Join(parts, " ")
	for _, a := range v.Attrs {
		s += " .attribute(" + a.String() + ")"
	}
	if v.Init != nil {
		s += " = " + v.Init.InitText()
	}
	return s + ";"
}

func paramDecl(p *ptx.Param) string {
	s := ".param"
	if p.Align != 0 {
		s += " .align " + strconv.Itoa(p.Align)
	}
	if p.Ptr != nil {
		s += " " + p.Type.String() + " .ptr" + p.Ptr.Space.String()
		if p.Ptr.Align != 0 {
			s += " .align " + strconv.Itoa(p.Ptr.Align)
		}
		return s + " " + p.Name
	}
	s += " " + p.Type.String() + " " + p.Name
	if p.Len > 0 {
		s += "[" + strconv.Itoa(p.Len) + "]"
	}
	return s
}

func protoDecl(p *ptx.Proto) string {
	var rets []string
	for i, t := range p.Ret {
		rets = append(rets, ".param "+t.String()+" _r"+strconv.Itoa(i))
	}
	var args []string
	for i, t := range p.Params {
		args = append(args, ".param "+t.String()+" _p"+strconv.Itoa(i))
	}
	s := p.Name + ": .callprototype "
	if len(rets) > 0 {
		s += "(" + strings.Join(rets, ", ") + ") "
	}
	s += "_ (" + strings.Join(args, ", ") + ")"
	if p.NoReturn {
		s += " .noreturn"
	}
	return s + ";"
}

func sectionDecl(s *ptx.Section) string {
	var b strings.Builder
	b.WriteString(".section " + s.Name + "\n{\n")
	for i := 0; i < len(s.Data); i += bytesPerLn {
		end := i + bytesPerLn
		if end > len(s.Data) {
			end = len(s.Data)
		}
		parts := make([]string, 0, end-i)
		for _, c := range s.Data[i:end] {
			parts = append(parts, fmt.Sprintf("0x%02x", c))
		}
		b.WriteString(indent + ".b8 " + strings.Join(parts, ", ") + ";\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// ---- Callables ------------------------------------------------------------

func (p *Printer) kernel(b *strings.Builder, k *ptx.Kernel) {
	if s := k.Linkage.String(); s != "" {
		b.WriteString(s + " ")
	}
	b.WriteString(".entry " + k.Name + "(\n")
	for i, prm := range k.Params {
		b.WriteString(indent + paramDecl(prm))
		if i < len(k.Params)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString(")\n")
	p.tuning(b, &k.Callable)
	p.body(b, k.Body)
}

func (p *Printer) function(b *strings.Builder, f *ptx.Func) {
	if s := f.Linkage.String(); s != "" {
		b.WriteString(s + " ")
	}
	b.WriteString(".func ")
	if len(f.Ret) > 0 {
		var rets []string
		for _, r := range f.Ret {
			rets = append(rets, paramDecl(r))
		}
		b.WriteString("(" + strings.Join(rets, ", ") + ") ")
	}
	b.WriteString(f.Name + "(")
	var args []string
	for _, prm := range f.Params {
		args = append(args, paramDecl(prm))
	}
	b.WriteString(strings.Join(args, ", ") + ")")
	if f.NoReturn {
		b.WriteString(" .noreturn")
	}
	b.WriteString("\n")
	p.tuning(b, &f.Callable)
	if f.Body == nil {
		b.WriteString(";\n")
		return
	}
	p.body(b, f.Body)
}

func (p *Printer) tuning(b *strings.Builder, c *ptx.Callable) {
	if !c.MaxNTid.IsZero() {
		b.WriteString(".maxntid " + c.MaxNTid.String() + "\n")
	}
	if !c.ReqNTid.IsZero() {
		b.WriteString(".reqntid " + c.ReqNTid.String() + "\n")
	}
	if c.MinNCTAPerSM != 0 {
		b.WriteString(".minnctapersm " + strconv.Itoa(c.MinNCTAPerSM) + "\n")
	}
	if c.MaxNReg != 0 {
		b.WriteString(".maxnreg " + strconv.Itoa(c.MaxNReg) + "\n")
	}
	if !c.ReqNCTAPerCluster.IsZero() {
		b.WriteString(".reqnctapercluster " + c.ReqNCTAPerCluster.String() + "\n")
	}
	if c.MaxClusterRank != 0 {
		b.WriteString(".maxclusterrank " + strconv.Itoa(c.MaxClusterRank) + "\n")
	}
	if c.ExplicitCluster {
		b.WriteString(".explicitcluster\n")
	}
	for _, a := range c.Attrs {
		b.WriteString(".attribute(" + a.String() + ")\n")
	}
	for _, pr := range c.Pragmas {
		b.WriteString(".pragma " + strconv.Quote(pr) + ";\n")
	}
}

// ---- Bodies ---------------------------------------------------------------

func (p *Printer) body(b *strings.Builder, bd *ptx.Body) {
	b.WriteString("{\n")

	for _, c := range bd.Regs.Classes() {
		b.WriteString(fmt.Sprintf("%s.reg %-6s %%%s<%d>;\n",
			indent, c.Type.String(), c.Prefix, c.Count+1))
	}
	for _, n := range bd.Regs.NamedRegs() {
		b.WriteString(fmt.Sprintf("%s.reg %-6s %%%s;\n", indent, n.Type.String(), n.Name))
	}
	if len(bd.Regs.Classes())+len(bd.Regs.NamedRegs()) > 0 && len(bd.Locals) > 0 {
		b.WriteString("\n")
	}
	for _, v := range bd.Locals {
		b.WriteString(indent + varDecl(v) + "\n")
	}
	if bd.Len() > 0 {
		b.WriteString("\n")
	}

	p.items(b, bd.Items(), indent)
	b.WriteString("}\n")
}

func (p *Printer) items(b *strings.Builder, items []ptx.Item, pad string) {
	for _, it := range items {
		switch x := it.(type) {
		case *ptx.Instr:
			b.WriteString(p.instr(x, pad))
		case *ptx.LabelBind:
			b.WriteString(x.Label.Name() + ":\n")
		case *ptx.LocDir:
			b.WriteString(pad + locDir(x) + "\n")
		case *ptx.BranchTargets:
			var names []string
			for _, t := range x.Targets {
				names = append(names, t.Name())
			}
			b.WriteString(pad + x.Name + ": .branchtargets " + strings.Join(names, ", ") + ";\n")
		case *ptx.CallTargets:
			var names []string
			for _, t := range x.Targets {
				names = append(names, t.Name)
			}
			b.WriteString(pad + x.Name + ": .calltargets " + strings.Join(names, ", ") + ";\n")
		case *ptx.Pragma:
			var qs []string
			for _, s := range x.Strings {
				qs = append(qs, strconv.Quote(s))
			}
			b.WriteString(pad + ".pragma " + strings.Join(qs, ", ") + ";\n")
		case *ptx.Block:
			b.WriteString(pad + "{\n")
			for _, v := range x.Locals {
				b.WriteString(pad + indent + varDecl(v) + "\n")
			}
			p.items(b, x.Items, pad+indent)
			b.WriteString(pad + "}\n")
		}
	}
}

func (p *Printer) instr(in *ptx.Instr, pad string) string {
	var b strings.Builder
	b.WriteString(pad)

	head := in.Mnemonic()
	if g := in.Pred.Text(); g != "" {
		head = g + " " + head
	}
	b.WriteString(head)

	ops := in.Operands()
	if len(ops) > 0 {
		if n := opColumn - len(head); n > 0 {
			b.WriteString(strings.Repeat(" ", n))
		} else {
			b.WriteString(" ")
		}
		parts := make([]string, len(ops))
		for i, o := range ops {
			parts[i] = o.Text()
		}
		b.WriteString(strings.Join(parts, ", "))
	}
	b.WriteString(";")
	if p.comments && in.Comment != "" {
		b.WriteString(" // " + in.Comment)
	}
	b.WriteString("\n")
	return b.String()
}

func locDir(d *ptx.LocDir) string {
	s := ".loc " + strconv.Itoa(d.File.Index) + " " +
		strconv.Itoa(d.Line) + " " + strconv.Itoa(d.Col)
	if d.Func != nil {
		s += ", function_name " + d.Func.Name()
		if d.FuncOff != 0 {
			s += "+" + strconv.FormatInt(d.FuncOff, 10)
		}
	}
	if d.Inlined != nil {
		s += ", inlined_at " + strconv.Itoa(d.Inlined.File.Index) + " " +
			strconv.Itoa(d.Inlined.Line) + " " + strconv.Itoa(d.Inlined.Col)
	}
	return s
}