// Package text prints a ptx.Module as .ptx assembly source. PTX has no
// binary encoding — the text produced here is the interchange format —
// so output is deterministic and byte-stable for a given IR.
package text

import (
	"fmt"
	"strings"

	"github.com/vertex-language/ir/ptx"
)

// Printer serializes one module. Configure with the With* options, then
// call Print.
type Printer struct {
	m        *ptx.Module
	comments bool
	header   string
	lint     bool
	warnings []string
}

// NewPrinter returns a printer for m with the default header.
func NewPrinter(m *ptx.Module) *Printer {
	return &Printer{m: m, comments: true, header: "Generated by vertex"}
}

// WithComments enables/disables trailing "//" comments from Instruction.Comment.
func (p *Printer) WithComments(on bool) *Printer { p.comments = on; return p }

// WithHeader overrides the leading header comment. Empty disables it.
func (p *Printer) WithHeader(h string) *Printer { p.header = h; return p }

// WithLint enables advisory version-gating warnings (never errors),
// retrievable via Warnings after Print.
func (p *Printer) WithLint(on bool) *Printer { p.lint = on; return p }

// Warnings returns lint notes collected during the last Print.
func (p *Printer) Warnings() []string { return p.warnings }

const (
	indent = "    "
	opCol  = 16 // column at which operands start
)

// Print renders the module as PTX assembly.
func (p *Printer) Print() (string, error) {
	m := p.m
	p.warnings = nil
	if m.AddressSize != 32 && m.AddressSize != 64 {
		return "", fmt.Errorf("ptx/text: invalid .address_size %d (must be 32 or 64)", m.AddressSize)
	}

	var b strings.Builder

	if p.header != "" {
		b.WriteString("//\n// " + p.header + "\n//\n")
	}
	b.WriteString(".version " + m.Version.String() + "\n")

	tgt := ".target " + m.Target.String()
	for _, o := range m.TargetOpts {
		tgt += ", " + string(o)
	}
	b.WriteString(tgt + "\n")
	b.WriteString(fmt.Sprintf(".address_size %d\n", m.AddressSize))

	if m.BlocksAreClusters {
		if p.lint && !m.Version.GTE(ptx.ISA90) {
			p.warn(".blocksareclusters requires ISA >= 9.0 (module is %s)", m.Version)
		}
		b.WriteString(".blocksareclusters\n")
	}

	for i, name := range m.Files.Names {
		b.WriteString(fmt.Sprintf(".file %d %q\n", i+1, name))
	}

	for _, v := range m.Globals.Items {
		b.WriteString("\n" + p.variable(v, "") + "\n")
	}
	for _, f := range m.Functions.Items {
		b.WriteString("\n")
		p.function(&b, f)
	}
	for _, k := range m.Kernels.Items {
		b.WriteString("\n")
		p.kernel(&b, k)
	}
	return b.String(), nil
}

func (p *Printer) warn(format string, args ...any) {
	p.warnings = append(p.warnings, fmt.Sprintf(format, args...))
}

// ---- declarations -------------------------------------------------------

func (p *Printer) variable(v ptx.Variable, ind string) string {
	parts := []string{}
	if l := v.Linkage.String(); l != "" {
		parts = append(parts, l)
	}
	parts = append(parts, v.Space.String())
	for _, a := range v.Attrs {
		parts = append(parts, ".attribute(."+string(a)+")")
	}
	if v.Align > 0 {
		parts = append(parts, fmt.Sprintf(".align %d", v.Align))
	}
	parts = append(parts, v.Type.String(), v.Name)
	s := ind + strings.Join(parts, " ")
	switch {
	case v.Len > 0:
		s += fmt.Sprintf("[%d]", v.Len)
	case v.Len < 0:
		s += "[]"
	}
	if v.Init != nil {
		s += " = " + v.Init.InitText()
	}
	return s + ";"
}

func param(pr ptx.Param) string {
	s := ".param " + pr.Type.String()
	if pr.Ptr != nil {
		s += " .ptr " + pr.Ptr.Space.String()
		if pr.Ptr.Align > 0 {
			s += fmt.Sprintf(" .align %d", pr.Ptr.Align)
		}
	} else if pr.Align > 0 {
		s += fmt.Sprintf(" .align %d", pr.Align)
	}
	s += " " + pr.Name
	if pr.Len > 0 {
		s += fmt.Sprintf("[%d]", pr.Len)
	}
	return s
}

func (p *Printer) signature(b *strings.Builder, c *ptx.Callable, kind, retClause string) {
	head := ""
	if l := c.Linkage.String(); l != "" {
		head = l + " "
	}
	head += kind
	if retClause != "" {
		head += " " + retClause
	}
	head += " " + c.Name
	if len(c.Params.Items) == 0 {
		b.WriteString(head + "()")
		return
	}
	b.WriteString(head + "(\n")
	for i, pr := range c.Params.Items {
		b.WriteString(indent + param(pr))
		if i < len(c.Params.Items)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString(")")
}

func perfDirectives(c *ptx.Callable) []string {
	var d []string
	if c.MaxNTid != [3]int{} {
		d = append(d, fmt.Sprintf(".maxntid %d, %d, %d", c.MaxNTid[0], c.MaxNTid[1], c.MaxNTid[2]))
	}
	if c.ReqNTid != [3]int{} {
		d = append(d, fmt.Sprintf(".reqntid %d, %d, %d", c.ReqNTid[0], c.ReqNTid[1], c.ReqNTid[2]))
	}
	if c.MinNCTAPerSM > 0 {
		d = append(d, fmt.Sprintf(".minnctapersm %d", c.MinNCTAPerSM))
	}
	if c.MaxNReg > 0 {
		d = append(d, fmt.Sprintf(".maxnreg %d", c.MaxNReg))
	}
	if c.ReqNCTAPerCluster != [3]int{} {
		d = append(d, fmt.Sprintf(".reqnctapercluster %d, %d, %d",
			c.ReqNCTAPerCluster[0], c.ReqNCTAPerCluster[1], c.ReqNCTAPerCluster[2]))
	}
	if c.ExplicitCluster {
		d = append(d, ".explicitcluster")
	}
	return d
}

func (p *Printer) kernel(b *strings.Builder, k *ptx.Kernel) {
	p.signature(b, &k.Callable, ".entry", "")
	p.finishCallable(b, &k.Callable, "")
}

func (p *Printer) function(b *strings.Builder, f *ptx.Function) {
	ret := ""
	if f.Ret != nil {
		ret = "(" + param(*f.Ret) + ")"
	}
	p.signature(b, &f.Callable, ".func", ret)
	extra := ""
	if f.NoReturn {
		extra = ".noreturn"
	}
	p.finishCallable(b, &f.Callable, extra)
}

func (p *Printer) finishCallable(b *strings.Builder, c *ptx.Callable, extra string) {
	for _, d := range perfDirectives(c) {
		b.WriteString(" " + d)
	}
	if extra != "" {
		b.WriteString(" " + extra)
	}
	if c.Code == nil {
		b.WriteString(";\n") // declaration only
		return
	}
	b.WriteString("\n{\n")
	p.body(b, c.Code)
	b.WriteString("}\n")
}

// ---- body ------------------------------------------------------------------

func (p *Printer) body(b *strings.Builder, cb *ptx.CodeBuilder) {
	// Ranged .reg declarations, one per register class.
	classes := cb.Regs.Classes()
	width := 0
	for _, c := range classes {
		if n := len(c.Type.String()); n > width {
			width = n
		}
	}
	for _, nr := range cb.Regs.NamedRegs() {
		if n := len(nr.Type.String()); n > width {
			width = n
		}
	}
	for _, c := range classes {
		b.WriteString(fmt.Sprintf("%s.reg %-*s %%%s<%d>;\n",
			indent, width, c.Type.String(), c.Prefix, c.Count+1))
	}
	for _, nr := range cb.Regs.NamedRegs() {
		b.WriteString(fmt.Sprintf("%s.reg %-*s %%%s;\n", indent, width, nr.Type.String(), nr.Name))
	}
	for _, v := range cb.Locals.Items {
		b.WriteString(p.variable(v, indent) + "\n")
	}
	if len(classes) > 0 || len(cb.Regs.NamedRegs()) > 0 || len(cb.Locals.Items) > 0 {
		b.WriteString("\n")
	}

	items := cb.Items
	for i, it := range items {
		switch x := it.(type) {
		case *ptx.BlankLine:
			b.WriteString("\n")
		case *ptx.LabelBind:
			b.WriteString(x.Label.Name() + ":\n")
		case *ptx.LocDirective:
			b.WriteString(fmt.Sprintf("%s.loc %d %d %d\n", indent, x.File, x.Line, x.Col))
		case *ptx.BranchTargets:
			names := make([]string, len(x.Targets))
			for j, t := range x.Targets {
				names[j] = t.Name()
			}
			b.WriteString(indent + x.Name + ": .branchtargets " + strings.Join(names, ", ") + ";\n")
		case *ptx.Instruction:
			b.WriteString(indent + p.instruction(x) + "\n")
			// Readability: blank line after a branch, unless a label or
			// explicit blank follows immediately.
			if strings.HasPrefix(x.Opcode, "bra") && i+1 < len(items) {
				switch items[i+1].(type) {
				case *ptx.LabelBind, *ptx.BlankLine:
				default:
					b.WriteString("\n")
				}
			}
		}
	}
	// Blank line before any label bind for readability.
	// (Handled in a second pass would complicate streaming; instead the
	// branch rule above plus explicit cb.Blank() cover common layouts.)
}

func (p *Printer) instruction(ins *ptx.Instruction) string {
	if ins.Raw != "" {
		line := ins.Raw
		if ins.Guard != "" {
			line = ins.Guard + " " + line
		}
		return p.withComment(line, ins.Comment)
	}
	prefix := ins.Opcode
	if ins.Guard != "" {
		prefix = ins.Guard + " " + prefix
	}
	line := prefix
	if len(ins.Operands) > 0 {
		if pad := opCol - len(prefix); pad > 0 {
			line += strings.Repeat(" ", pad)
		} else {
			line += " "
		}
		parts := make([]string, len(ins.Operands))
		for i, o := range ins.Operands {
			parts[i] = o.Text()
		}
		line += strings.Join(parts, ", ")
	}
	return p.withComment(line+";", ins.Comment)
}

func (p *Printer) withComment(line, comment string) string {
	if p.comments && comment != "" {
		return line + "    // " + comment
	}
	return line
}